config/routes.rb
TeamRoleControl::Engine.routes.draw do
  root to: "users#index"
  resources :roles
  resources :teams
  resources :users, except: [:new, :create, :destroy]
  resources :permissions, only: [:index]

  resources :team_permissions, only: [] do
    get 'search', on: :collection
  end

  resources :teams, as: :team, only: [] do
    resources :team_permissions, only: [] do
      get 'search', on: :collection
    end
    resources :roles do
      resources :team_permissions, only: [:index]
    end
  end


end

app/models/concerns/team_role_control/support.rb
# frozen_string_literal: true

module TeamRoleControl
  module Support
    extend ActiveSupport::Concern

    included do
      def has_team_role?(team, role)
        roles.joins(:team).where("team_role_control_teams.name = '?' AND team_role_control_roles.name = '?'", team, role).any?
      end
    end

    module ClassMethods
      def team_role_appointees(*_args)
        # self.send :include, TeamRoleControl::UserQueries

        has_many :user_roles, class_name: '::TRC::UserRole'
        has_many :roles, through: :user_roles, class_name: '::TRC::Role'

        has_many :teams, -> { distinct }, through: :roles, class_name: '::TRC::Team'
        has_many :team_permissions, -> { distinct }, through: :roles, class_name: '::TRC::TeamPermission'
        has_many :permissions, -> { distinct }, through: :team_permissions, class_name: '::TRC::Permission'

        has_many :overrides, class_name: '::TRC::Override'
        has_many :special_permissions, -> { special }, class_name: '::TRC::Override'
        has_many :revoked_permissions, -> { revoked }, class_name: '::TRC::Override'

        has_many :overriden_team_permissions, through: :overrides, source: :team_permission, class_name: '::TRC::TeamPermission'
        has_many :overriden_teams, through: :overriden_team_permissions, source: :team, class_name: '::TRC::Team'

        has_many :special_permission_overrides,
                 through: :special_permissions,
                 source: :team_permission,
                 class_name: '::TRC::TeamPermission'

        has_many :revoked_permission_overrides,
                 through: :revoked_permissions,
                 source: :team_permission,
                 class_name: '::TRC::TeamPermission'
      end

      def assigned_to_team
        belongs_to :team, class_name: '::TRC::Team'
      end
    end
  end

  # module UserQueries
  #   def all_permissions
  #     # If they have the team permission through the role and the override is_permitted, then remove redundancy.
  #     # CURRENTLY NOT WORKING CORRECTLY
  #     overrides.where.not(
  #       id: team_permissions.pluck(:id),
  #       is_permitted: true
  #     )
  #   end
  # end
end

app/models/team_role_control/application_record.rb
# frozen_string_literal: true

module TeamRoleControl
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/team_role_control/override.rb
# frozen_string_literal: true

module TeamRoleControl
  class Override < ApplicationRecord
    belongs_to :team_permission
    belongs_to :user

    validates :team_permission_id, uniqueness: { scope: :user_id }

    scope :special, -> { where(is_permitted: true) }
    scope :revoked, -> { where(is_permitted: false) }
  end
end

app/models/team_role_control/permission.rb
# frozen_string_literal: true

module TeamRoleControl
  class Permission < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search, against: [:action, :object]

    has_many :team_permissions, dependent: :delete_all
    has_many :users, through: :team_permissions, inverse_of: :permissions
    has_many :roles, -> { distinct }, through: :team_permissions
    validates :object, uniqueness: { scope: :action, message: "Object/Action permission already exists!" }

    after_save :create_team_permissions

    private

    def create_team_permissions
      TeamPermission.create_for_all_teams(self)
    end
  end
end

app/models/team_role_control/role.rb
# frozen_string_literal: true

module TeamRoleControl
  class Role < ApplicationRecord
    has_many :user_roles, dependent: :destroy
    has_many :users, through: :user_roles

    belongs_to :team
    has_many :role_team_permissions, dependent: :destroy
    has_many :team_permissions, through: :role_team_permissions
    has_many :permissions, through: :team_permissions

    validates :name, presence: true

    def display_name
      "#{name} - #{team.name}"
    end
  end
end

app/models/team_role_control/role_team_permission.rb
# frozen_string_literal: true

module TeamRoleControl
  class RoleTeamPermission < ApplicationRecord
    belongs_to :role
    belongs_to :team_permission
  end
end

app/models/team_role_control/team.rb
# frozen_string_literal: true

module TeamRoleControl
  class Team < ApplicationRecord
    has_many :roles, dependent: :destroy
    has_many :users, through: :roles
    has_many :team_permissions, dependent: :destroy

    accepts_nested_attributes_for :roles, allow_destroy: true

    validates :name, presence: true
  end
end

app/models/team_role_control/team_permission.rb
# frozen_string_literal: true

module TeamRoleControl
  class TeamPermission < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search, associated_against: {
               permission: [:object, :action],
               team: :name,
             }

    belongs_to :team
    belongs_to :permission

    has_many :role_team_permissions
    has_many :roles, through: :role_team_permissions
    has_many :users, through: :roles, inverse_of: :team_permissions

    has_many :overrides, dependent: :destroy

    def display_name
      "#{permission.action.capitalize} #{permission.object}"
    end

    def display_name_with_team
      "#{display_name} for #{team.name}"
    end

    def self.create_for_all_teams(permission)
      Team.all.each do |team|
        create!(
          permission: permission,
          team: team,
        )
      end
    end
  end
end

app/models/team_role_control/user_role.rb
# frozen_string_literal: true

module TeamRoleControl
  class UserRole < ApplicationRecord
    belongs_to :user
    belongs_to :role

    validates :role_id, uniqueness: { scope: :user_id }
  end
end

app/controllers/concerns/team_role_control/permittable.rb
# frozen_string_literal: true

module TeamRoleControl
  module Permittable
    extend ActiveSupport::Concern
    # TODO: look at this

    # module ClassMethods
    def is_permissible?(user: current_user, team: current_user.teams, action: action_name, object: get_controllers_model)
      team_permission = user.team_permissions.joins(:permission).where(
        team: team,
        team_role_control_permissions: {
          object: object,
          action: action
        }
      )

      override = TRC::Override.find_by(team_permission: team_permission, user: user)

      if override
        return override.is_permitted
      else
        return team_permission.any?
      end
    end

    private

    def get_controllers_model
      respond_to?(:controller_path) && controller_path.classify
    end
    # end
  end
end

app/controllers/team_role_control/application_controller.rb
module TeamRoleControl
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    layout "team_role_control/main"

    def ignoring_teams
      TeamRoleControl.configuration.ignore_teams
    end

    helper_method :ignoring_teams

  end
end

app/controllers/team_role_control/permissions_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class PermissionsController < ApplicationController

    def index
      @permissions = Permission.all

      if params[:term]
        @permissions = {
          results: Permission.search( params[:term] )
        }
      end

      respond_to do |format|
        format.json { render json: @permissions }
      end
    end

  end
end

app/controllers/team_role_control/roles_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class RolesController < ApplicationController
    before_action :set_team
    before_action :set_role, only: [:show, :edit, :update, :destroy]

    # GET team/:team_id/roles
    def index
      redirect_to team_path(@team)
    end

    # GET team/:team_id/roles/1
    def show
    end

    # GET team/:team_id/roles/new
    def new
      @role = @team.roles.build
    end

    # GET team/:team_id/roles/1/edit
    def edit
    end

    # POST team/:team_id/roles
    def create
      @role = @team.roles.build(role_params)

      if @role.save
        redirect_to @team, notice: 'Role was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT team/:team_id/roles/1
    def update
      if @role.update(role_params)
        redirect_to @team, notice: 'Role was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE team/:team_id/roles/1
    def destroy
      @role.destroy
      redirect_to @team, notice: 'Role was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_team
        @team = ignoring_teams ? Team.first : Team.find(params[:team_id])
      end

      def set_role
          @role = @team.roles.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def role_params
        params.require(:role).permit(:name, :description, team_permission_ids: [])
      end
  end
end

app/controllers/team_role_control/team_permissions_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class TeamPermissionsController < ApplicationController
    before_action :set_roles_team_permission_ids

    def index
      @role = Role.find params[:role_id]
      team_permissions = @role.team_permissions.where.not(id: @roles_tp_ids)

      @html_string = render_to_string( 
        partial: "team_role_control/users/permissions_check_boxes",
        locals: {
          object: :user, 
          method: "revoked_permission_override_ids", 
          collection: team_permissions,
          is_new: true
        }
      )

      render json: { template: @html_string }
    end


    def search
      @team_permissions = {
        results: TeamPermission.where(team_id: params[:team_id]).search( params[:term] )
      }

      if params[:role_ids] || params[:exclude_ids]
        exclude_ids = params[:exclude_ids] || []
        all_excluded_ids = (exclude_ids + @roles_tp_ids)
        @team_permissions[:results] = @team_permissions[:results].where.not(id: all_excluded_ids)
      end

      render json: @team_permissions, methods: :display_name
    end


    private


    def set_roles_team_permission_ids
      @roles_tp_ids = Role.where(id: params[:role_ids]).map { |role| role.team_permissions.pluck(:id) }.flatten || []
    end

  end
end

app/controllers/team_role_control/teams_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class TeamsController < ApplicationController
    before_action :set_team, only: [:show, :edit, :update, :destroy]
    before_action :set_users, only: [:new, :edit]

    # GET /teams
    def index
      @teams = Team.all
    end

    # GET /teams/1
    def show
    end

    # GET /teams/new
    def new
      @team = Team.new
    end

    # GET /teams/1/edit
    def edit
    end

    # POST /teams
    def create
      @team = Team.new(team_params)

      if @team.save
        redirect_to teams_url, notice: 'Team was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /teams/1
    def update
      if @team.update(team_params)
        redirect_to @team, notice: 'Team was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /teams/1
    def destroy
      @team.destroy
      redirect_to teams_url, notice: 'Team was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_team
        @team = ignoring_teams ? Team.first : Team.find(params[:id])
      end

      def set_users
        @users = ::User.all
      end

      # Only allow a trusted parameter "white list" through.
      def team_params
        params.require(:team).permit(:name, :description, roles_attributes: [:name, :description, :id, :_destroy])
      end
  end
end

app/controllers/team_role_control/users_controller.rb
require_dependency "team_role_control/application_controller"

# Currently there no support for User creation since users are added to the database via a third party source.

module TeamRoleControl
  class UsersController < ::TeamRoleControl::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    def index
      @users = ::User.all
    end

    # GET /users/1
    def show
    end

    # # GET /users/new
    # def new
    #   @user = ::User.new
    # end

    # GET /users/1/edit
    # Can only currently edit Role and Team Settings
    def edit
    end

    # # POST /users
    # def create
    #   @user = ::User.new(user_params)

    #   if @user.save
    #     redirect_to @user, notice: 'User was successfully created.'
    #   else
    #     render :new
    #   end
    # end

    # PATCH/PUT /users/1
    def update
      if user_update_transaction
        redirect_to user_path(@user), notice: "User was successfully updated."
      else
        render :edit
      end
    end

    # # DELETE /users/1
    # def destroy
    #   @user.destroy
    #   redirect_to users_url, notice: 'User was successfully destroyed.'
    # end

    private

    def user_update_transaction
      updated = false

      ActiveRecord::Base.transaction do
        @user.overrides.destroy_all
        updated = @user.update(user_params)
      end
      return updated
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = ::User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(
        role_ids: [],
        special_permission_override_ids: [],
        revoked_permission_override_ids: [],
      )
    end
  end
end

app/helpers/team_role_control/application_helper.rb
module TeamRoleControl
  module ApplicationHelper
    include ::ApplicationHelper

    ICON_NAME = {
      teams: 'group',
      users: 'contacts',
      roles: 'transfer_within_a_station',
      permissions: 'vpn_key',
      edit: 'edit'
    }

    def material_icon type
      icon_name = ICON_NAME.key?(type) ? ICON_NAME[type.to_sym] : type.to_s
      content_tag(:i, icon_name, class: 'material-icons')
    end
  end
end

app/helpers/team_role_control/layouts_helper.rb
module TeamRoleControl
  module LayoutsHelper

    def inside_layout(layout = "application", &block)
      render inline: capture(&block), layout: "layouts/#{layout}"
    end

    def active_tab? tab_name
      if ignoring_teams && (controller_name === 'teams')
        namespace = 'roles'
      elsif !ignoring_teams && (controller_name === 'roles')
        namespace = 'teams'
      else
        namespace = controller_name
      end
      
      tab_name === namespace ? 'is-active' : ''
    end

    def trc_header **locals, &haml
      if block_given?
        render layout: 'team_role_control/shared/header', locals: locals, &haml
      else
        render partial: 'team_role_control/shared/header', locals: locals
      end
    end
    
  end
end

app/views/team_role_control/teams/_form.html.haml
= form_for @team, html: {class: 'trc-Form'} do |f|
  .u-whiteBlock
    .trc-Form-group
      = f.label :name
      = f.text_field :name  
      - if @team.errors.any? && @team.errors.key?(:name)
        .trc-error-message= "Name #{@team.errors[:name].first}"

    .trc-Form-group
      = f.label :description
      = f.text_area :description
      - if @team.errors.any? && @team.errors.key?(:description)
        .trc-error-message= "Description #{@team.errors[:description].first}"

  .u-block
    = trc_header icon: :roles, title: 'Roles', lighten: true, thin: true do
      = link_to_add_association f, :roles, class: 'trc-Button--clear', data: {association_insertion_node: '.trc-List--cards', association_insertion_method: 'prepend' } do
        = material_icon :add
        Add Role


    %ul.trc-List--cards
      = f.fields_for :roles do |role_f|
        = render 'role_fields', f: role_f

  .trc-Form-actions
    = link_to 'Cancel', :back, class: 'trc-Button--clear'
    = f.submit 'Save', class: 'trc-Button'

app/views/team_role_control/teams/_role_fields.html.haml
%li.trc-List--cards-item.nested-fields
  .trc-Form-group
    = f.text_field :name, placeholder: "Name"
    - if @team.errors.any? && @team.errors.key?('roles.name')
      .trc-error-message= "Name #{@team.errors['roles.name'].first}"

  .trc-Form-group
    = f.text_area :description, placeholder: "Description"
    - if @team.errors.any? && @team.errors.key?('roles.description')
      .trc-error-message= "Description #{@team.errors['roles.description'].first}"
  .u-centerText
    = link_to_remove_association f, class: 'trc-Button--clear', onclick: '' do
      = material_icon :remove_circle
      Remove

app/views/team_role_control/teams/edit.html.haml
= trc_header icon: :teams, title: 'Edit Team', lighten: true

= render 'form'

app/views/team_role_control/teams/index.html.haml
= trc_header icon: :teams, title: 'TEAMS', lighten: true do
  = link_to 'New Team', new_team_path, class: 'trc-Button'

%ul.trc-List
  - @teams.each do | team |
    %li.trc-List-item{onclick: "location.href='#{team_path(team)}'"}
      .trc-Header
        .trc-Header-title
          %h5= team.name
          %small= team.description
          %div
            %small= "#{team.users.count} Users, #{team.roles.count} Roles"
        .trc-Header-actions
          = link_to edit_team_path(team) do
            = material_icon :edit

          = link_to team, method: :delete, data: { confirm: 'Are you sure?' } do
            = material_icon :clear

app/views/team_role_control/teams/new.html.haml
= trc_header icon: :teams, title: 'New Team', lighten: true

= render 'form'

app/views/team_role_control/teams/show.html.haml
- if !ignoring_teams
  = trc_header icon: :teams, title: @team.name.titleize, description: @team.description do
    = link_to edit_team_path(@team) do
      = material_icon :edit

  - title = "#{@team.roles.count} Role#{'s' if @team.roles.count > 1}"

  = trc_header title: title, lighten: true do
    = link_to new_team_role_path(@team), class: 'trc-Button--clear' do
      = material_icon :add
      New Role

- else
  = trc_header icon: :roles, title: 'ROLES', lighten: true do
    = link_to "New Role", new_team_role_path(@team), class: 'trc-Button'


%ul.trc-List
  - @team.roles.each do | role |
    %li.trc-List-item
      .trc-Header
        .trc-Header-icon
          = material_icon :roles
        .trc-Header-title
          = link_to team_role_path(@team, role) do
            %h5= role.name
        .trc-Header-actions
          = link_to edit_team_role_path(@team, role) do
            = material_icon :edit
          = link_to team_role_path(@team, role), method: :delete, data: { confirm: 'Are you sure?' } do
            = material_icon :clear

      %table
        %thead
          %tr
            %th User
            %th.u-centerText Permissions
        %tbody
          - role.users.each do |user|
            %tr{onclick: "location.href='#{user_path(user)}'"}
              %td= user.send(TeamRoleControl.configuration.user_display_name_method)
              %td.u-centerText= user.team_permissions.where(team: @team).count

      %details.trc-Details
        %summary.is-lighter
          = material_icon :permissions
          %div Permissions

        .trc-CheckboxGroup
          - role.team_permissions.each do |permit|
            .trc-Checkbox
              .trc-Checkbox-cover= permit.display_name
        %small *Listed are all permissions granted to this role.