config/routes.rb
TeamRoleControl::Engine.routes.draw do
  root to: "users#index"
  resources :roles
  resources :teams
  resources :users, except: [:new, :create, :destroy]
  resources :permissions, only: [:index]

  resources :team_permissions, only: [] do
    get 'search', on: :collection
  end

  resources :teams, as: :team, only: [] do
    resources :team_permissions, only: [] do
      get 'search', on: :collection
    end
    resources :roles do
      resources :team_permissions, only: [:index]
    end
  end


end

app/models/concerns/team_role_control/support.rb
# frozen_string_literal: true

module TeamRoleControl
  module Support
    extend ActiveSupport::Concern

    included do
      def has_team_role?(team, role)
        roles.joins(:team).where("team_role_control_teams.name = '?' AND team_role_control_roles.name = '?'", team, role).any?
      end
    end

    module ClassMethods
      def team_role_appointees(*_args)
        # self.send :include, TeamRoleControl::UserQueries

        has_many :user_roles, class_name: '::TRC::UserRole'
        has_many :roles, through: :user_roles, class_name: '::TRC::Role'

        has_many :teams, -> { distinct }, through: :roles, class_name: '::TRC::Team'
        has_many :team_permissions, -> { distinct }, through: :roles, class_name: '::TRC::TeamPermission'
        has_many :permissions, -> { distinct }, through: :team_permissions, class_name: '::TRC::Permission'

        has_many :overrides, class_name: '::TRC::Override'
        has_many :special_permissions, -> { special }, class_name: '::TRC::Override'
        has_many :revoked_permissions, -> { revoked }, class_name: '::TRC::Override'

        has_many :overriden_team_permissions, through: :overrides, source: :team_permission, class_name: '::TRC::TeamPermission'
        has_many :overriden_teams, through: :overriden_team_permissions, source: :team, class_name: '::TRC::Team'

        has_many :special_permission_overrides,
                 through: :special_permissions,
                 source: :team_permission,
                 class_name: '::TRC::TeamPermission'

        has_many :revoked_permission_overrides,
                 through: :revoked_permissions,
                 source: :team_permission,
                 class_name: '::TRC::TeamPermission'
      end

      def assigned_to_team
        belongs_to :team, class_name: '::TRC::Team'
      end
    end
  end

  # module UserQueries
  #   def all_permissions
  #     # If they have the team permission through the role and the override is_permitted, then remove redundancy.
  #     # CURRENTLY NOT WORKING CORRECTLY
  #     overrides.where.not(
  #       id: team_permissions.pluck(:id),
  #       is_permitted: true
  #     )
  #   end
  # end
end

app/models/team_role_control/application_record.rb
# frozen_string_literal: true

module TeamRoleControl
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/team_role_control/override.rb
# frozen_string_literal: true

module TeamRoleControl
  class Override < ApplicationRecord
    belongs_to :team_permission
    belongs_to :user

    validates :team_permission_id, uniqueness: { scope: :user_id }

    scope :special, -> { where(is_permitted: true) }
    scope :revoked, -> { where(is_permitted: false) }
  end
end

app/models/team_role_control/permission.rb
# frozen_string_literal: true

module TeamRoleControl
  class Permission < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search, against: [:action, :object]

    has_many :team_permissions, dependent: :delete_all
    has_many :users, through: :team_permissions, inverse_of: :permissions
    has_many :roles, -> { distinct }, through: :team_permissions
    validates :object, uniqueness: { scope: :action, message: "Object/Action permission already exists!" }

    after_save :create_team_permissions

    private

    def create_team_permissions
      TeamPermission.create_for_all_teams(self)
    end
  end
end

app/models/team_role_control/role.rb
# frozen_string_literal: true

module TeamRoleControl
  class Role < ApplicationRecord
    has_many :user_roles, dependent: :destroy
    has_many :users, through: :user_roles

    belongs_to :team
    has_many :role_team_permissions, dependent: :destroy
    has_many :team_permissions, through: :role_team_permissions
    has_many :permissions, through: :team_permissions

    validates :name, presence: true

    def display_name
      "#{name} - #{team.name}"
    end
  end
end

app/models/team_role_control/role_team_permission.rb
# frozen_string_literal: true

module TeamRoleControl
  class RoleTeamPermission < ApplicationRecord
    belongs_to :role
    belongs_to :team_permission
  end
end

app/models/team_role_control/team.rb
# frozen_string_literal: true

module TeamRoleControl
  class Team < ApplicationRecord
    has_many :roles, dependent: :destroy
    has_many :users, through: :roles
    has_many :team_permissions, dependent: :destroy

    accepts_nested_attributes_for :roles, allow_destroy: true

    validates :name, presence: true
  end
end

app/models/team_role_control/team_permission.rb
# frozen_string_literal: true

module TeamRoleControl
  class TeamPermission < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search, associated_against: {
               permission: [:object, :action],
               team: :name,
             }

    belongs_to :team
    belongs_to :permission

    has_many :role_team_permissions
    has_many :roles, through: :role_team_permissions
    has_many :users, through: :roles, inverse_of: :team_permissions

    has_many :overrides, dependent: :destroy

    def display_name
      "#{permission.action.capitalize} #{permission.object}"
    end

    def display_name_with_team
      "#{display_name} for #{team.name}"
    end

    def self.create_for_all_teams(permission)
      Team.all.each do |team|
        create!(
          permission: permission,
          team: team,
        )
      end
    end
  end
end

app/models/team_role_control/user_role.rb
# frozen_string_literal: true

module TeamRoleControl
  class UserRole < ApplicationRecord
    belongs_to :user
    belongs_to :role

    validates :role_id, uniqueness: { scope: :user_id }
  end
end

app/controllers/concerns/team_role_control/permittable.rb
# frozen_string_literal: true

module TeamRoleControl
  module Permittable
    extend ActiveSupport::Concern
    # TODO: look at this

    # module ClassMethods
    def is_permissible?(user: current_user, team: current_user.teams, action: action_name, object: get_controllers_model)
      team_permission = user.team_permissions.joins(:permission).where(
        team: team,
        team_role_control_permissions: {
          object: object,
          action: action
        }
      )

      override = TRC::Override.find_by(team_permission: team_permission, user: user)

      if override
        return override.is_permitted
      else
        return team_permission.any?
      end
    end

    private

    def get_controllers_model
      respond_to?(:controller_path) && controller_path.classify
    end
    # end
  end
end

app/controllers/team_role_control/application_controller.rb
module TeamRoleControl
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    layout "team_role_control/main"

    def ignoring_teams
      TeamRoleControl.configuration.ignore_teams
    end

    helper_method :ignoring_teams

  end
end

app/controllers/team_role_control/permissions_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class PermissionsController < ApplicationController

    def index
      @permissions = Permission.all

      if params[:term]
        @permissions = {
          results: Permission.search( params[:term] )
        }
      end

      respond_to do |format|
        format.json { render json: @permissions }
      end
    end

  end
end

app/controllers/team_role_control/roles_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class RolesController < ApplicationController
    before_action :set_team
    before_action :set_role, only: [:show, :edit, :update, :destroy]

    # GET team/:team_id/roles
    def index
      redirect_to team_path(@team)
    end

    # GET team/:team_id/roles/1
    def show
    end

    # GET team/:team_id/roles/new
    def new
      @role = @team.roles.build
    end

    # GET team/:team_id/roles/1/edit
    def edit
    end

    # POST team/:team_id/roles
    def create
      @role = @team.roles.build(role_params)

      if @role.save
        redirect_to @team, notice: 'Role was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT team/:team_id/roles/1
    def update
      if @role.update(role_params)
        redirect_to @team, notice: 'Role was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE team/:team_id/roles/1
    def destroy
      @role.destroy
      redirect_to @team, notice: 'Role was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_team
        @team = ignoring_teams ? Team.first : Team.find(params[:team_id])
      end

      def set_role
          @role = @team.roles.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def role_params
        params.require(:role).permit(:name, :description, team_permission_ids: [])
      end
  end
end

app/controllers/team_role_control/team_permissions_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class TeamPermissionsController < ApplicationController
    before_action :set_roles_team_permission_ids

    def index
      @role = Role.find params[:role_id]
      team_permissions = @role.team_permissions.where.not(id: @roles_tp_ids)

      @html_string = render_to_string( 
        partial: "team_role_control/users/permissions_check_boxes",
        locals: {
          object: :user, 
          method: "revoked_permission_override_ids", 
          collection: team_permissions,
          is_new: true
        }
      )

      render json: { template: @html_string }
    end


    def search
      @team_permissions = {
        results: TeamPermission.where(team_id: params[:team_id]).search( params[:term] )
      }

      if params[:role_ids] || params[:exclude_ids]
        exclude_ids = params[:exclude_ids] || []
        all_excluded_ids = (exclude_ids + @roles_tp_ids)
        @team_permissions[:results] = @team_permissions[:results].where.not(id: all_excluded_ids)
      end

      render json: @team_permissions, methods: :display_name
    end


    private


    def set_roles_team_permission_ids
      @roles_tp_ids = Role.where(id: params[:role_ids]).map { |role| role.team_permissions.pluck(:id) }.flatten || []
    end

  end
end

app/controllers/team_role_control/teams_controller.rb
require_dependency "team_role_control/application_controller"

module TeamRoleControl
  class TeamsController < ApplicationController
    before_action :set_team, only: [:show, :edit, :update, :destroy]
    before_action :set_users, only: [:new, :edit]

    # GET /teams
    def index
      @teams = Team.all
    end

    # GET /teams/1
    def show
    end

    # GET /teams/new
    def new
      @team = Team.new
    end

    # GET /teams/1/edit
    def edit
    end

    # POST /teams
    def create
      @team = Team.new(team_params)

      if @team.save
        redirect_to teams_url, notice: 'Team was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /teams/1
    def update
      if @team.update(team_params)
        redirect_to @team, notice: 'Team was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /teams/1
    def destroy
      @team.destroy
      redirect_to teams_url, notice: 'Team was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_team
        @team = ignoring_teams ? Team.first : Team.find(params[:id])
      end

      def set_users
        @users = ::User.all
      end

      # Only allow a trusted parameter "white list" through.
      def team_params
        params.require(:team).permit(:name, :description, roles_attributes: [:name, :description, :id, :_destroy])
      end
  end
end

app/controllers/team_role_control/users_controller.rb
require_dependency "team_role_control/application_controller"

# Currently there no support for User creation since users are added to the database via a third party source.

module TeamRoleControl
  class UsersController < ::TeamRoleControl::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    def index
      @users = ::User.all
    end

    # GET /users/1
    def show
    end

    # # GET /users/new
    # def new
    #   @user = ::User.new
    # end

    # GET /users/1/edit
    # Can only currently edit Role and Team Settings
    def edit
    end

    # # POST /users
    # def create
    #   @user = ::User.new(user_params)

    #   if @user.save
    #     redirect_to @user, notice: 'User was successfully created.'
    #   else
    #     render :new
    #   end
    # end

    # PATCH/PUT /users/1
    def update
      if user_update_transaction
        redirect_to user_path(@user), notice: "User was successfully updated."
      else
        render :edit
      end
    end

    # # DELETE /users/1
    # def destroy
    #   @user.destroy
    #   redirect_to users_url, notice: 'User was successfully destroyed.'
    # end

    private

    def user_update_transaction
      updated = false

      ActiveRecord::Base.transaction do
        @user.overrides.destroy_all
        updated = @user.update(user_params)
      end
      return updated
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = ::User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(
        role_ids: [],
        special_permission_override_ids: [],
        revoked_permission_override_ids: [],
      )
    end
  end
end

app/helpers/team_role_control/application_helper.rb
module TeamRoleControl
  module ApplicationHelper
    include ::ApplicationHelper

    ICON_NAME = {
      teams: 'group',
      users: 'contacts',
      roles: 'transfer_within_a_station',
      permissions: 'vpn_key',
      edit: 'edit'
    }

    def material_icon type
      icon_name = ICON_NAME.key?(type) ? ICON_NAME[type.to_sym] : type.to_s
      content_tag(:i, icon_name, class: 'material-icons')
    end
  end
end

app/helpers/team_role_control/layouts_helper.rb
module TeamRoleControl
  module LayoutsHelper

    def inside_layout(layout = "application", &block)
      render inline: capture(&block), layout: "layouts/#{layout}"
    end

    def active_tab? tab_name
      if ignoring_teams && (controller_name === 'teams')
        namespace = 'roles'
      elsif !ignoring_teams && (controller_name === 'roles')
        namespace = 'teams'
      else
        namespace = controller_name
      end
      
      tab_name === namespace ? 'is-active' : ''
    end

    def trc_header **locals, &haml
      if block_given?
        render layout: 'team_role_control/shared/header', locals: locals, &haml
      else
        render partial: 'team_role_control/shared/header', locals: locals
      end
    end
    
  end
end

app/views/team_role_control/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    .trc-expand-section
      %summary
        = material_icon :settings
        %h4 Settings

      - team_roles = TRC::Team.all.inject(Hash.new([])) {|hsh, team| hsh[team.id] = @user.roles.where(team_id: team.id).pluck(:id); hsh}

      #trc-user-settings.trc-expand-section__body{data: {initial_roles: team_roles.to_json}}
        - TRC::Role.all.group_by(&:team).each do |team, roles|
          %details.trc-field-group
            %summary.trc-icon-title
              = material_icon :teams
              %h6= team.name
            = f.collection_check_boxes :role_ids, roles, :id, :name  do |box|
              .trc-check-box.tabify
                = box.label do
                  = box.check_box(class: "-filter-", data: {role: box.object.id, team: team.id})
                  .trc-check-box__cover
                    = material_icon :roles
                    = box.object.name

            .trc-expand-section.trc-filter-select{data: {team: team.id}}
              / = material_icon :permissions
              .row
                .column
                  %h6 Role Permissions
                  = f.collection_check_boxes "revoked_permission_override_ids", team.team_permissions, :id, :display_name do |box|
                    .trc-check-box.darkened{data: {roles: box.object.roles.map(&:id)}}
                      = box.label do
                        = box.check_box
                        .trc-check-box__cover
                          = box.object.display_name

                .trc-additional-permissions.column.column-25.-center-
                  %h6 Additional
                  %select.trc-Search{data: {path: permissions_path}}
                  = f.collection_check_boxes "special_permission_override_ids", @user.special_permissions.map(&:team_permission).reject {|tp| tp.team != team}, :id, :display_name do |box|
                    .trc-check-box{data: {roles: box.object.roles.map(&:id)}}
                      = box.label do
                        = box.check_box
                        .trc-check-box__cover
                          = material_icon :check
                          = box.object.display_name

            / .trc-expand-section.trc-filter-select{data: {team: team.id}}
            /   %summary
            /     = material_icon :permissions
            /     / %h4 Permissions
            /     / %small *Click to revoke the permissions.

            /   - # Display role-selected permissions and click to revoke
            /   = f.collection_check_boxes "revoked_permission_override_ids", team.team_permissions, :id, :display_name do |box|
            /     .trc-check-box.darkened{data: {roles: box.object.roles.map(&:id)}}
            /       = box.label do
            /         = box.check_box
            /         .trc-check-box__cover
            /           = material_icon :roles
            /           = box.object.display_name

            /   - # Display unselected role permissions and click to activate
            /   = f.collection_check_boxes "special_permission_override_ids", team.team_permissions, :id, :display_name do |box|
            /     .trc-check-box{data: {roles: box.object.roles.map(&:id)}}
            /       = box.label do
            /         = box.check_box
            /         .trc-check-box__cover
            /           = material_icon :check
            /           = box.object.display_name

  .actions.float-right
    = f.submit 'Save'

:coffeescript
  new TRC.UserSettings

app/views/team_role_control/users/_permissions_check_boxes.html.haml
- classes ||= ''

= collection_check_boxes object, method, collection, :id, :display_name do |box|
  .trc-Checkbox{data: {id: box.object.id}}
    = box.label do
      - if defined? force_check
        = box.check_box(checked: force_check)
      - else
        = box.check_box
      .trc-Checkbox-cover{class: classes}
        = yield
        = box.object.display_name

app/views/team_role_control/users/_settings_form.html.haml
= form_for :user, method: :patch, url: user_path(@user) do |f|

  %section#js-UserSettings
    = render partial: 'team_role_control/shared/header', locals: {icon: :settings, title: "User Settings", lighten: true}

    - element = ignoring_teams ? 'article' : 'details.trc-Details'
    - TRC::Role.all.group_by(&:team).each do |team, roles|
      - haml_tag element, class: "js--team", data: {team_id: team.id} do
        - unless ignoring_teams
          %summary.u-iconTextAlign.u-topBorder--darker.u-block
            = material_icon :teams
            %h6= team.name

        .trc-Form-group
          .js--roles
            = f.collection_check_boxes :role_ids, roles, :id, :name  do |box|
              .trc-Checkbox--tab{data: {team_permissions_path: team_role_team_permissions_path(team, box.object.id)}}
                = box.label do
                  = box.check_box(class: "-filter-")
                  .trc-Checkbox-cover
                    = material_icon :roles
                    = box.object.name

          - revoked_permissions = @user.team_permissions.where(team: team)
          - additional_permissions = @user.special_permissions.map(&:team_permission).reject {|tp| tp.team != team}

          .trc-Row
            .trc-Column.is-60.u-whiteBlock
              .trc-CheckboxGroup--strike.js--role-permissions
                .u-textRow
                  %h6 Role Permissions
                  %small
                    %i *Select permission to revoke.

                %h5.u-block.u-centerText.js--message No Role for this Team
                // checked state is revoked
                = render 'permissions_check_boxes', object: :user, method: "revoked_permission_override_ids", collection: revoked_permissions, classes: 'is-revokable stuff'

            .trc-Column.is-40.u-whiteBlock.u-leftBorder
              .trc-CheckboxGroup--toggle-display.u-centerText.js--additional-permissions
                %h6 Additional
                %select.trc-Search{style: "width: 100%;", data: {placeholder: "Search permissions..", path: search_team_team_permissions_path(team.id)}}
                .js--additional-permission-container
                  = render 'permissions_check_boxes', object: :user, method: "special_permission_override_ids", collection: additional_permissions, classes: "u-noMarginX", force_check: true do
                    = material_icon(:close)


  .trc-Form-actions
    = link_to 'Cancel', :back, class: 'trc-Button--clear'
    = f.submit 'Save', class: 'trc-Button'

  

app/views/team_role_control/users/edit.html.haml
- display_name = @user.send(TeamRoleControl.configuration.user_display_name_method)

= render partial: 'team_role_control/shared/header', locals: {icon: :users, title: display_name}

= render 'settings_form'

app/views/team_role_control/users/index.html.haml
= trc_header icon: :users, title: 'USERS', lighten: true

%ul.trc-List
  - @users.each do | user |
    %li.trc-List-item{onclick: "location.href='#{user_path(user)}'"}
      .trc-Header
        .trc-Header-title
          %h5= user.send(TeamRoleControl.configuration.user_display_name_method)
          %small= user.email
          %div
            %small= "#{user.teams.count.to_s + ' Teams, ' unless ignoring_teams}#{user.roles.count} Roles, #{user.team_permissions.count} Permissions, #{user.overrides.count} Overrides"
        .trc-Header-actions
          = link_to edit_user_path(user) do
            = material_icon :settings

app/views/team_role_control/users/new.html.haml
.trc-content-header.clearfix
  %h4.-strong- New user

= render 'settings_form'

= link_to 'Back', users_path

app/views/team_role_control/users/show.html.haml
- user_name = @user.send(TeamRoleControl.configuration.user_display_name_method)

= trc_header icon: :users, title: user_name, details: @user.email do
  = link_to edit_user_path(@user) do
    = material_icon :settings

- uniq_teams_through_overrides = @user.overriden_teams.uniq

- if uniq_teams_through_overrides.count >= 1
  - uniq_teams_through_overrides -= @user.teams.uniq
  
- if ignoring_teams
  - title = "#{@user.roles.count} Role#{'s' if @user.roles.count != 1}"
- else
  - title = "#{@user.teams.count} Team#{'s' if @user.teams.count != 1}"

= render partial: 'team_role_control/shared/header', locals: {title: title, lighten: true} 

%ul.trc-List
  - if ignoring_teams
    - @user.roles.each do | role |
      %li.trc-List-item
        .trc-Header
          .trc-Header-icon
            = material_icon :roles
          .trc-Header-title
            = link_to team_role_path(role.team.id, role.id) do
              %h5= role.name
            %small= role.description

        - team_overrides = @user.overrides.where(team_permission_id: role.team.team_permissions.pluck(:id))

        - if team_overrides.count >= 1
          %details.trc-Details
            %summary.is-lighter
              = material_icon :permissions
              %div Permissions

            .trc-CheckboxGroup
              - team_overrides.reverse.each do |override|
                - permit = override.team_permission
                .trc-Checkbox{class: ("is-checked" unless override.is_permitted)}
                  .trc-Checkbox-cover= permit.display_name
            %small *Listed are revoked permissions or permissions granted outside the user's provided roles.

  - else
    - @user.teams.each do | team |
      %li.trc-List-item
        .trc-Header
          .trc-Header-icon
            = material_icon :teams
          .trc-Header-title
            = link_to team_path(team) do
              %h5= team.name

        - user_roles = TRC::UserRole.where(user_id: @user.id, role_id: team.roles.pluck(:id))
        - if user_roles.count >= 1
          %table
            %thead
              %tr
                %th Roles
                %th Description

            %tbody
              - user_roles.each do |user_role|
                - role = user_role.role
                %tr{onclick: "location.href='#{team_role_path(team, role)}'"}
                  %td= role.name
                  %td= role.description


        - team_overrides = @user.overrides.where(team_permission_id: team.team_permissions.pluck(:id))

        - if @user.team_permissions.where(team: team).count
          %details.trc-Details
            %summary.is-lighter
              = material_icon :permissions
              %div Permissions

            - if team_overrides.count >= 1
              .trc-CheckboxGroup--strike
                - team_overrides.reverse.each do |override|
                  - permit = override.team_permission
                  .trc-Checkbox{class: ("is-checked" unless override.is_permitted)}
                    .trc-Checkbox-cover= permit.display_name

                - @user.team_permissions.where(team: team) do |permission|
                  %p Thing
                  .trc-Checkbox
                    .trc-Checkbox-cover= permission.display_name

              %small *Listed are revoked permissions or permissions granted outside the user's provided roles.